name: CICD

on:
  workflow_dispatch:  
  
jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        run: echo "Cloning the code"
      
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build using Docker
        run: echo "building Docker"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Testing on the machine
        run: echo "Testing the code"
        
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy on the server
        run: echo "Deploying"
    
